In [13]:
# 📌 Step 0: Load the Dataset
import pandas as pd

# Load Titanic dataset (you can replace with your own path or use seaborn's version)
df = pd.read_csv('D:\\Phani\\etechguild\\syllabus\\demo\\lessons\\python\\EDA\\Titanic-Dataset.csv') 
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
#checklist
# Checklist: Track your progress
cleaning_steps = {
    "Fix Rows": False,
    "Fix Columns": False,
    "Fix Missing Values": False,
    "Standardize Values": False,
    "Fix Invalid Values": False,
    "Filter Data": False
}

In [15]:
#fix rows
# Remove irrelevant rows (if any)
# Titanic dataset is clean in terms of summary/footer rows, but here's how you'd do it:
df = df[df['Name'].notna()]  # Example: Remove rows where 'Name' is missing

# Reset index after row removal
df.reset_index(drop=True, inplace=True)

In [16]:
#fix columns
# Rename columns for clarity
df.rename(columns={'Pclass': 'Passenger_Class', 'Fare': 'Ticket_Fare'}, inplace=True)

# Merge columns: Create Full Name
df['Full_Name'] = df['Name']

# Split column: Extract Title from Name
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

# Drop unnecessary columns
df.drop(columns=['Cabin'], inplace=True)  # Cabin has too many missing values

In [19]:
#fix missing values
# Check missing values
df.isnull().sum()

# Fill missing Age with median
df.fillna({'Age': df['Age'].median()}, inplace=True)


# Fill missing Embarked with mode
df.fillna({'Embarked': df['Embarked'].mode()[0]}, inplace=True)

In [20]:
# Standardize gender values
df['Sex'] = df['Sex'].str.lower()

# Standardize Embarked values
df['Embarked'] = df['Embarked'].replace({'S': 'Southampton', 'C': 'Cherbourg', 'Q': 'Queenstown'})

In [21]:
# Remove invalid ages (e.g., negative values)
df = df[df['Age'] >= 0]

# Filter passengers with fare > 0
df = df[df['Ticket_Fare'] > 0]

# Filter dataset to only adult passengers
df_adults = df[df['Age'] >= 18]

In [22]:
# Final cleaned dataset preview
df.head()

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Fare,Embarked,Full_Name,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Southampton,"Braund, Mr. Owen Harris",Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,Cherbourg,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Southampton,"Heikkinen, Miss. Laina",Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,Southampton,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Southampton,"Allen, Mr. William Henry",Mr